### ISSUE TITLE
Xychorium Ores drop 0 EXP

### ISSUE THREAD

**Issue by soarynDerp** [Soaryn/XyCraftTracker#1]
**Describe the bug**
When harvesting any type of Xychorium Ore, they do not drop EXP.

**To Reproduce**
1. Summon/Place/Find one of the ores listed above
2. Mine said ore with a pickaxe that can successfully mine the ore (In my case I used Netherite)
3. Receive the item(s) but no EXP

**Expected behavior**
I believe that the Xychorium Ore should drop EXP, as do all ores that drop their final product (ie. Redstone and Lapis) 

**Screenshots**
![image](https://user-images.githubusercontent.com/52632286/187574577-6f9422f0-ee39-473b-ad2e-3df697048d65.png)
![image](https://user-images.githubusercontent.com/52632286/187574605-374ee0c8-8e7d-4239-8ea5-7d6303c078b6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - XyCraft Core Version: [e.g. v0.5.0]

**Additional context**

**Comment by Soaryn** [comment]
Added (finally) in v6.x
