### ISSUE TITLE
Blasting recipe for Aluminum Ingot has same cooking time as smelting

### ISSUE THREAD

**Issue by nikita488** [Soaryn/XyCraftTracker#10]
**Describe the bug**
Blasting recipe for Aluminum Ingot has same cooking time as smelting.

**Expected behavior**
Vanilla has half of smelting time for ore blasting recipes, so Raw Iron to Iron Ingot in Furnace has 200 ticks for smelting, and 100 ticks for blasting, should be same for Aluminum.

**Desktop (please complete the following information):**
 - XyCraft Core Version: v0.5.3

**Comment by Soaryn** [comment]
Already fixed
