### ISSUE TITLE
Question: Is there a way to disable CTM for some blocks?

### ISSUE THREAD

**Issue by TwistedKindn3ss** [Soaryn/XyCraftTracker#11]
Sorry if this is out of place, just wondering if there was a config to disable the CTM somewhere. Didnt see any guides/config file.

**Comment by Soaryn** [comment]
Mmm that is powered by Resource packs, so really it is done by changing the models to be just a normal block with the *_single.png variants as the texture. I could make a resource pack provided with the mod that does so, but do note all of the textures built are with the intention to have a connected texture 😅

**Comment by Soaryn** [comment]
This is Resource pack driven. So while the idea of being able to disable certain blocks from Connected textures would be neat, there isn't a lot of configurability in a resource pack.

Perfect world would have a resource pack with customizable features without having to have multiple packs. For now closing this as I don't see many options to provide this smoothly
