### ISSUE TITLE
[0.5.17 / Startup crash] Game crashing on startup.

### ISSUE THREAD

**Issue by murao-kun** [Soaryn/XyCraftTracker#12]
**Describe the bug**
Game crashing on startup

**Desktop (please complete the following information):**
 - OS: Windows 10/11
 - XyCraft Core Version: 0.5.17

**Additional context**
[Uploading crash-2022-10-28_00.09.51-client.txt…]()

**Comment by Soaryn** [comment]
Curiously, try updating to the latest forge. I may have forgotten to have it added as a dependency, but even then it should be fine on the older versions. The crash log didn't properly load so I can't even diagnose 😅

**Comment by Soaryn** [comment]
Assuming this is the fix, I am actually running the game with the current version on stream. So it seems it is either a mod incompatibility, which would seem odd, or it was my lack of forcing the newer version of forge it is compiled to. Sorry for the inconveniences, but without the crash log (it never uploaded fully) I can't say for certain what caused your issue
