### ISSUE TITLE
request: horizontal/rotatable lamp poles

### ISSUE THREAD

**Issue by redgoblin88** [Soaryn/XyCraftTracker#14]
i am aware that these being horizontal is because of a forge bug and they should be vertical, but using them in my elevator shaft, they fit quite well being horizontal, being vertical i don't think they would work

would it be possible to add a "wrench" feature so it rotates the pole itself? (because right now, it is only in one direction, if i placed these on the 90 degree sides of the shaft, they would be "poking in")

![2023-01-29_18 04 28](https://user-images.githubusercontent.com/13396472/215346527-5b33962f-2168-4e4a-ac33-ea3da60fd9b3.png)

xycraft core: 0.5.17
xycraft world: 0.5.17
forge: 43.2.3

**Comment by Soaryn** [comment]
Completed. Adding in next public update.
