### ISSUE TITLE
Question about Kivi generation

### ISSUE THREAD

**Issue by warplord** [Soaryn/XyCraftTracker#15]
Question, not really an issue - what the spawn conditions for Kivi? At what Y lvl and biome/dim does it spawn?

**Comment by Soaryn** [comment]
Assuming what I have in my code is the same as the public version (it should be) then it should appear around y0-60 in large clumps, though it may have a problem with dimensions. As I don't have any vanilla dimensions to test against that have natural stone.

```json
{
  "feature": "xycraft_world:ore_kivi",
  "placement": [
    {
      "type": "minecraft:rarity_filter",
      "chance": 2
    },
    {
      "type": "minecraft:in_square"
    },
    {
      "type": "minecraft:height_range",
      "height": {
        "type": "minecraft:uniform",
        "max_inclusive": {
          "absolute": 60
        },
        "min_inclusive": {
          "absolute": 0
        }
      }
    },
    {
      "type": "minecraft:biome"
    }
  ]
}
```

**Comment by Soaryn** [comment]
No further inquiries made. The numbers will be increasing in v0.6.0 But there is still some time before that.
