### ISSUE TITLE
Should Xycraft Ores have EMC Values? *World

### ISSUE THREAD

**Issue by Flexico** [Soaryn/XyCraftTracker#16]
**Is your feature request related to a problem? Please describe.**
Even when I'm not using ProjectE, I find it cathartic for every material to have a numbered value~

**Describe the solution you'd like**
The ProjectE config file (as well as a few in-game commands) allows you to set the EMC value for any item, so technically I already added this myself, but I wanted your opinion on how much they should be worth. I picked 1024 for the gems (half as much as gold), and 128 for both Kivi and Aluminum ingots (same as copper). ProjectE automatically calculates the value of things that have recipes containing items/blocks that have a value themselves, so that covered pretty much all of Xycraft's blocks and items! (Excepting ore blocks and raw aluminum.)

**Please ensure to label the feature where it would fit best: Examples - core, world, override**
World

**Comment by Soaryn** [comment]
EMC is too generalized to have a set value really. This is a pack by pack basis. I'll look into what they should be and potentially add a default. But I'd say it is too early to set a value on my side given that the acquisition of the resource will change.
