### ISSUE TITLE
Jar has lower case 'c' for XyCraft.

### ISSUE THREAD

**Issue by Soaryn** [Soaryn/XyCraftTracker#2]
Each build jar has a lower case 'c' and should be instead XyCraft_World-x.y.z.jar

**Comment by nikita488** [comment]
Also Mod Display Name has lowercase 'c', should be XyCraft
![image](https://user-images.githubusercontent.com/6237881/187666119-72553735-9fe1-4086-a8c7-a454dc1facd8.png)
