### ISSUE TITLE
[Bug]: Tank fluid fade too early on smaller render distance

### ISSUE THREAD

**Issue by nikita488** [Soaryn/XyCraftTracker#21]
### XyCraft Module

Machines

### Minecraft Version

1.20.1

### Severity

Odd Results

### Describe the Suggestion

When you move away from tank, fluid stored in it fades too early before it gets out of player view on small render distance.

### Reproduction Steps

1. Build a tank
2. Set Render Distance to 2-4
3. Fill tank with any opaque fluid
4. Move away from it and see

### Screenshots and Videos

Tested with Render Distance: 2 chunks

https://github.com/Soaryn/XyCraftTracker/assets/6237881/7a59d0f8-5cca-4422-94b3-96654bea1923

**Comment by Soaryn** [comment]
This one is a little tricky, and I really need to implement a proper fix for it, but I have for now bumped up the range a bit in v0.6.21.
Will improve later
