### ISSUE TITLE
[Bug]: RGB Viewer is fully opaque

### ISSUE THREAD

**Issue by nikita488** [Soaryn/XyCraftTracker#22]
### XyCraft Module

World

### Minecraft Version

1.20.1

### Severity

Odd Results

### Describe the Suggestion

In the previous versions, RGB Viewer was translucent, now it's fully opaque.

### Reproduction Steps

Place RGB Viewer in World or see in the inventory

### Screenshots and Videos

![image](https://github.com/Soaryn/XyCraftTracker/assets/6237881/68e8e275-4d12-4079-8def-0761b8b5f604)

**Comment by Soaryn** [comment]
Wooops! I was trying to solve a different bug and modified the wrong block🙃🙃🙃🙃 will fix

**Comment by Soaryn** [comment]
Fixed in v0.6.21
