### ISSUE TITLE
[Bug]: Tanks not loading on client correctly on world load

### ISSUE THREAD

**Issue by nikita488** [Soaryn/XyCraftTracker#23]
### XyCraft Module

Machines

### Minecraft Version

1.20.1

### Severity

Odd Results

### Describe the Suggestion

When you near by tanks and exit to main menu, then load back, you cannot see Tank bounding box, Tank fluid and cannot right click on it until you break any tank block and reactivate Valve OR go far away from it and back.
Also that SOMETIMES happens when you place Nether Portal near working tanks, go into it, and go back. They are not working anymore on client.

### Reproduction Steps

1. Build tanks near you
2. Exit to Main Menu
3. Load back to your world
4. Tanks are now not working
5. Teleport far far away from them and teleport back to your tanks
6. Tanks are now loaded correctly on client

### Screenshots and Videos

https://github.com/Soaryn/XyCraftTracker/assets/6237881/676ba1ce-88b2-47c2-a5dc-4e23050a94d5

Example with Nether Portal: https://i.imgur.com/iMBg4xY.mp4

**Comment by Soaryn** [comment]
Hmmm I fixed this already, and not happening using replication steps 🤔

**Comment by nikita488** [comment]
I might mention that i created superflat world and teleported far away at x 10000 z 10000 from spawn area

**Comment by Soaryn** [comment]
That seems to be related

**Comment by Soaryn** [comment]
AH found a possible reason. onLoad is usually called first, but for some reason, when in high distances from the origin, getClientPacket is called before onLoad..... Debugging

**Comment by Soaryn** [comment]
Investigative fix for v0.6.21
