### ISSUE TITLE
[Suggestion]: resource generation rates

### ISSUE THREAD

**Issue by redgoblin88** [Soaryn/XyCraftTracker#26]
### XyCraft Module

World

### Describe the Suggestion

I am aware that in 0.6.22 of xycraft that ore generation was set to be very rare, which has changed to be more common in 0.6.23, but upon "sampling" the world (as seen in the screenshot taken at about Y16) there seems to be a LOT of xychorium, is this the intended quantity to generate?

### Screenshots and Videos

![2023-10-09_15 48 57](https://github.com/Soaryn/XyCraftTracker/assets/13396472/1ba8d628-e622-4739-9c1e-a8fcf71c11da)

**Comment by Soaryn** [comment]
I checked with the digital miner, so when you look at tit like this, you should see a lot. What does iron look like, or copper?

**Comment by redgoblin88** [comment]
![2023-10-10_13 20 05](https://github.com/Soaryn/XyCraftTracker/assets/13396472/608e98d2-7eb7-40a2-9aaf-7d262db12eff)
![2023-10-10_13 20 13](https://github.com/Soaryn/XyCraftTracker/assets/13396472/51d5189c-b6f8-47e4-9c8c-2ef9a0ac649d)
![2023-10-10_13 49 23](https://github.com/Soaryn/XyCraftTracker/assets/13396472/b33a0d90-b660-434c-a3e9-6091c3baf817)
![2023-10-10_13 49 50](https://github.com/Soaryn/XyCraftTracker/assets/13396472/0ee6fc67-72b0-42cf-9435-770230257b75)

Here it is with iron (ore replaced with iron blocks) and coal (replaced with coal blocks) i didnt do copper as they generate in bigger "lumps" and are also more frequent and bigger size in dripstone cave biome

**Comment by TheDeviantCrafter** [comment]
While trying to solve this problem in my own modpack, I made a datapack to disable aluminum:

[xycraft_world.zip](https://github.com/Soaryn/XyCraftTracker/files/13855502/xycraft_world.zip)

This one sets aluminum's ore vein size to 0, but you can change that or use the datapack to change the other ore values.

**Comment by Soaryn** [comment]
Doing a test of my own (1.20.4), the ore values are lower than most everything in vanilla as well as most mods. So I'm not sure this is something to lower.
