### ISSUE TITLE
[Bug]: Rotating Extractor breaks recipe

### ISSUE THREAD

**Issue by RoyalReject** [Soaryn/XyCraftTracker#28]
### XyCraft Module

Machines

### Minecraft Version

1.20.1

### Severity

Odd Results

### Describe the Suggestion

If you are setting up an Extractor recipe and don't place it in the correct orientation first the recipe does not work. 

### Reproduction Steps

We are playing Direwolf20 1.20 v1.10. 
We are doing the dragon egg recipe. 

Place chest. 
Place Extractor in correct orientation. 
Place dragon egg. 
Recipe works. 

Place chest. 
Place Extractor sideways. 
Rotate Extractor with any forge wrench to correct orientation. 
Place dragon egg. 
Recipe not found. 

### Screenshots and Videos

![image-1](https://github.com/Soaryn/XyCraftTracker/assets/32550284/b718980b-5d3d-4c2b-9545-2afc47cff227)

**Comment by Soaryn** [comment]
AH! Interesting. I'll need to fix that soon. Likely will start looking at that this weekend. Thanks :D

**Comment by Soaryn** [comment]
Found the culprit. Basically I'm caching the locations so that we don't keep having to offset over and over. Should be fixed in the next version, but I am unsure when that will be :)

For now, the work around is to place it as desired the first time. It is EXCEPTIONALLY annoying, but at least it has been identified!

**Comment by jlp1528** [comment]
I can't seem to get the extractor to work at all, even when following these directions. It turns yellow, that's it. What am I missing?

**Comment by jlp1528** [comment]
So reloading the world fixed it. Interesting!

**Comment by Soaryn** [comment]
This is guaranteed fixed in 1.20.4+ since I rewrote the entire system in the new Neo Forge ecosystem. This however will likely not  be backported as the entire system changed. Sorry about that.
