### ISSUE TITLE
[Bug]:  Laser IO node + Item Card + Basic Filter is next to a Fabricator

### ISSUE THREAD

**Issue by DinnerBeef** [Soaryn/XyCraftTracker#29]
### XyCraft Module

Machines

### Minecraft Version

1.20.1

### Severity

Crashing

### Describe the Suggestion

The server crashes when a Fabricator is next to a Laser IO node and that node has two Item Cards on the side of the Fabricator and a basic filter is placed into one of them. The server will crash in such a way that it gets stuck shutting down and generally must be force-killed.

### Reproduction Steps

Items needed: 1 Xycraft Fabricator, 1 Laser IO Node, 2 Item Cards, 1 Basic Filter

Place down the Fabricator (crafting grid is face up)
Fill in the processor binding recipe from JEI
Place Laser IO Node in front of it
Place 2 Item Cards in the Laser IO Node face toward the Fabricator (the tab that has it's icon)
Place a basic filter in the first item card

### Screenshots and Videos

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4048

**Comment by Soaryn** [comment]
This seems to be on Dire's side. I can try to add some additional protections, but this is purely on LaserIO for how he is checking if the inner card is empty.

Changing that should hopefully fix the issue. But until I finish my other project I am working on, I can't release another build atm.

**Comment by Soaryn** [comment]
This was in theory fixed on Dire's end since he was using some rather odd isEmpty work arounds :P Let me know if it is still causing issues!
