### ISSUE TITLE
[Bug]:  causing domum_ornamentum to loos images of blocks 

### ISSUE THREAD

**Issue by Tsumiki129** [Soaryn/XyCraftTracker#30]
### Minecraft Version

1.20.1

### Severity

Odd Results

### Describe the Suggestion

suggestions nothing past looking at the cause for bug

### Reproduction Steps

add domum_ornamentum and XyCraft override get the cutting block in creative and add glass 

![2023-11-06_19 37 42](https://github.com/Soaryn/XyCraftTracker/assets/147937268/92775793-f7ab-42f0-8767-966696a2fdc1)

![2023-11-06_19 38 38](https://github.com/Soaryn/XyCraftTracker/assets/147937268/0749c99f-7d04-4b82-b89d-45c2921f5555)

![2023-11-06_19 38 41](https://github.com/Soaryn/XyCraftTracker/assets/147937268/d4622a26-e8db-40e2-9221-be15908099f1)

**Comment by Soaryn** [comment]
Will take a look. Though unsure if this is our side or theirs. I'll start asking though :)

**Comment by Tsumiki129** [comment]
ok the mod is fine but wen adding yours it then brakes but like you said it could be one or the other thanks for the fast response and starting

**Comment by Soaryn** [comment]
Oh I hear you! It is mostly due to the fact we aren't doing anything special with item rendering. So this may be either our connected textures (which IS what we are overriding) but that shouldn't be breaking because glass has a different model :P

Hopefully it is resolvable, and if there is a problem my side, I'll do my best to fix it 👍

**Comment by Tsumiki129** [comment]
it was also reported  to have affected smooth stone as well how ever i did not test all blocks so i am unsure what other blocks for it could be affected

**Comment by Soaryn** [comment]
[No change]
I feel like this is still Domum having some assumptions of models, and am closing this for now, but do let me know if this is causing problems once 1.20.4 is up and running
