### ISSUE TITLE
Where does Kivi spawn or is it craftable?

### ISSUE THREAD

**Issue by sdruid** [Soaryn/XyCraftTracker#33]
I am currently playing a Modpack and they added your mod,  ver.  .6.22  on 1.20.1 java Minecraft.   I have scoured the interwebs for days looking for an answer to this.   Where does Kivi spawn or is it craftable?   If it spawns, is it in the overworld, nether, or some other dimension?   I have read the reddits, wiki is non existent, watched several tutorials and mod walk-throughs and have yet to find this answer.

Many thanks

**Comment by sdruid** [comment]
It randomly generates in the Overworld just like the Crystals

**Comment by cherixberry** [comment]
How does this translate in the Stoneblock 4 modpack? There is no overworld here...

**Comment by Soaryn** [comment]
That is up to stoneblock. Not up to vanilla XyCraft
