### ISSUE TITLE
[Suggestion]: Remove unnecessary duplicate recipes (also found one that uses the wrong item)

### ISSUE THREAD

**Issue by vizthex123** [Soaryn/XyCraftTracker#38]
### XyCraft Module

Override

### Describe the Suggestion

I noticed that almost every recipe has an `_r` version that mirrors it, and I'd suggest removing these as recipes are mirrored by default.

I also found that the Xychorium-Infused Chiseled Deepslate recipes use Planks instead of Deepslate. Everything else uses their intended blocks.

**Comment by vizthex123** [comment]
Also, condensing all the Xychorium-Infused Aluminum Brick recipes into a single one that accepts alternate items would be great.

**Comment by Soaryn** [comment]
Re Planks: Yep yep. Woops. I fixed that when we got to 20.4 sooo shouldn't be an issue in the future🙈

As for mirrored recipes, vanilla doesnt have a mirror by default iirc, so we add one tonmake it simpler to craft

**Comment by vizthex123** [comment]
> Re Planks: Yep yep. Woops. I fixed that when we got to 20.4 sooo shouldn't be an issue in the future🙈
> 
> As for mirrored recipes, vanilla doesnt have a mirror by default iirc, so we add one tonmake it simpler to craft

i'm pretty sure it does, cuz i tested it and i can craft mirrored recipes. Removed the mirrored ones with KubeJS, but i can still craft mirrored recipes (maybe forge is doing it? I dunno).

i reported the same mirrored recipes issue to the dev of Lightman's Currency a while ago and he removed them, but you can still mirror the recipes.

like i said, it's not a big deal - i just find it _really_ annoying lol. Same when devs don't add standard tags (haven't found any missing ones here though, which is nice. Saves me from having to fix them all lol).

will the plank recipe fix be on 1.20.1? Did fix it myself for now, but it'd be nice to have it be official.

**Comment by Soaryn** [comment]
1.20.1 is a frozen version. No changes will be back ported from 1.21.
Seems vanilla may have something for mirroring after all. Neat! Will go over my recipes to remove "duplicates" but this will again be fore 1.21+

**Comment by Soaryn** [comment]
Keep in mind, 1.20.1 version that is available is almost a year old. And the project structure has changed drastically It has been addressed in 0.7.24
