### ISSUE TITLE
[Suggestion]: Standardize names for all storage blocks

### ISSUE THREAD

**Issue by vizthex123** [Soaryn/XyCraftTracker#39]
### XyCraft Module

World

### Describe the Suggestion

They don't follow the normal standard of "Block of [Material]" (e.g. Block of Raw Aluminum). Would be nice it got fixed.

In addition, the gem items say "Gems" when it should be "Gem" as each gem item is 1 visually gem rather than multiple in a stack or combination.

**Comment by Soaryn** [comment]
Fixed in dev

**Comment by vizthex123** [comment]
noice.
