### ISSUE TITLE
[Bug]: LegacyRandomSource Concurrency issue

### ISSUE THREAD

**Issue by Saereth** [Soaryn/XyCraftTracker#41]
### Mod Title

Simple Weather

### Minecraft Version

1.20.4

### Severity

Crashing

### Describe the Suggestion

Occasionally we're getting some reports of crashing with simple weather due to LegacyRandomSource from multiple threads. This is unfortunately an inconsistent crash 

### Reproduction Steps

Just happens randomly on load. This was reported in FTB Neotech but I've experienced it in testing with a much smaller modlist as well. 

### Additional Context

originally reported on our tracker here:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5352

included crashlog:
https://github.com/user-attachments/files/15912168/crash-2024-06-20_10.32.23-client.txt

**Comment by Soaryn** [comment]
Investigating this still, but I feel like this may actually be a more concerning problem on the pack's end (though I may be able to mitigate my side a bit).

Ultimately I call `clientLevel.random` and that should be fine to call in `ClientTickEvent.Pre`, but something I feel is calling the same level.random in an off thread or more accurately not one of MC's client threads (I could be wrong, hence why the potential fix may resolve all issues)

I really don't know. Regardless there is either 2 things happening here:
- Minecraft added a thread use of clientlevel.random that I never encountered on FC
- A mod is doing silly threaded things on thread unsafe code.

**Comment by Soaryn** [comment]
After looking into it, as far as I can see this crash would happen as soon as someone accesses level.random on a separate thread, which should NOT be Simple Weather without some performance mod tweaking events. If tests come back indicating it is doing it still on separate threads from just Simple Weather, feel free to comment here and I can reopen the issue :) I looked for a few hours though and most of the devs I talked to indicated what we are doing in our scope is correct.

**Comment by Soaryn** [comment]
After looking into it, as far as I can see this crash would happen as soon as someone accesses level.random on a separate thread, which should NOT be Simple Weather without some performance mod tweaking events. If tests come back indicating it is doing it still on separate threads from just Simple Weather, feel free to comment here and I can reopen the issue :) I looked for a few hours though and most of the devs I talked to indicated what we are doing in our scope is correct.
