### ISSUE TITLE
[Bug]: MC loads into a Mojang Red Screen with Machines active.

### ISSUE THREAD

**Issue by unspunreality** [Soaryn/XyCraftTracker#42]
### Mod Title

XyCraft Machines

### Minecraft Version

1.20.4

### Severity

Odd Results

### Describe the Suggestion

For 1.21. Not sure what happened but isolated it to XyCraft machines. Load up MC and after doing all the loading bars/circling fox/etc, the game stays stuck at the Mojang Studios Red Screen, but the game is still active. Music plays in the background and I can click and interact with the game despite the splash being up.

### Reproduction Steps

Just loading the game normally with XyCraft Machines active. Tried with just Machines/Core/World active and no other mods and same issue. Red Mojang Studios splash screen, the progress bar anywhere between 80-99% filled, game sound in background and I can click 'something' in the background cause I get the button clicking sounds.

**Comment by Soaryn** [comment]
Can I get a log at all for when this happens?

**Comment by Soaryn** [comment]
My assumption thus far, is that something changed in Neo (during the beta phase here) that XyCraft was using before, but it is weird it isn't crashing hence why I need the logs :)

**Comment by unspunreality** [comment]
> My assumption thus far, is that something changed in Neo (during the beta phase here) that XyCraft was using before, but it is weird it isn't crashing hence why I need the logs :)

https://mclo.gs/aiFHnaB

Uhh, hopefully that helps? No crash so Im just providing the MC log that prism creates. I kept all my mods loaded cause there isnt any difference between all mods or not but I can also do without mods if that makes a difference. (Aside from machines + necessary ofcourse)

**Comment by Soaryn** [comment]
AH! So there were a lot of breaking changes in one of the most recent Neo versions ( `21.0.26`), I'll push a new build tonight, but this change also breaks things like JEI 0.9, so you may need to downgrade to `21.0.25` of neo for just a little while.

**Comment by Soaryn** [comment]
Clarity of what changed:
A few Access transformers, which are used to make things that are not accessible, accessible, were removed as they are in a set of things that should be less likely used. In my case I use one of the variables that WAS provided to add render layers to things. I can add it back on my side, just wasn't aware neo got rid of them in 0.26 :) 

This just means any mods using any of those fields (variables) will crash on load typically or when they inevitably call their variable use.

**Comment by unspunreality** [comment]
> AH! So there were a lot of breaking changes in one of the most recent Neo versions ( `21.0.26`), I'll push a new build tonight, but this change also breaks things like JEI 0.9, so you may need to downgrade to `21.0.25` of neo for just a little while.

Oh yeah. Im back on my 1.20.1 world cause JEI broke and is posted on their git. I fully expect stuff to break as 1.21 happens, neo changes, etc. Just hoping to do my own work by informing you/other mod makers when stuff breaks. So hopefully I did that correctly here.

**Comment by Soaryn** [comment]
Yep yep! Was meaning to push out a build since 14 versions have passed by, and with beta period that means anything and everything can break since the last version. :) So I appreciate the report.

As a note, (I need to add this to the report template) logs are always appreciated when possible

**Comment by Soaryn** [comment]
Fixed in `0.7.26` Requires `neo 21.0.37-beta`
