### ISSUE TITLE
Neoforge brake change again

### ISSUE THREAD

**Issue by castilio20** [Soaryn/XyCraftTracker#44]
### Mod Title

XyCraft Machines

### Minecraft Version

1.21.0

### Severity

Crashing

### NeoForge Version

0.42 i think the brake change is in 21.0.39` Replace PlantType system with SpecialPlantable interface and canSustainPlant block method (#971)
   
![Screenshot_25](https://github.com/Soaryn/XyCraftTracker/assets/76228548/abe25cfa-29eb-462e-95d7-a3df1d4ee7cc)

### Describe the Suggestion

fix the mod?(kinda weird thing to ask for a bug)

### Reproduction Steps

instal the mod

**Comment by Soaryn** [comment]
Will be pushing a build soon (`v0.7.27`), basically beta phase is breaking change every release of neo (as is expected).

**Comment by Soaryn** [comment]
Version `0.7.27` is released
