### ISSUE TITLE
InstancedIcosphere does not run shader.clear() when it is done

### ISSUE THREAD

**Issue by IMS212** [Soaryn/XyCraftTracker#46]
Due to how Iris functions, this means that it will permanently believe your shader is running, and essentially softlock the game due to not being able to run it's own shaders. This is partially an oversight on my part, but it may be good to fix it on your side just in case another mod relies on it.

**Comment by Soaryn** [comment]
Hmmm will look into it, definitely not calling that atm, but cant work at my pc until the AC is fixed

**Comment by IMS212** [comment]
No problem, Iris won't be released for NeoForge for a while; this isn't urgent.

**Comment by Soaryn** [comment]
Added the call at the end of the draw in `0.7.31` (unreleased) :) Seems to .... working at least on my end

**Comment by Soaryn** [comment]
Build with this change is likely going out tonight or tomorrow :)

**Comment by Soaryn** [comment]
Fixed in build that is in pending on CF
