### ISSUE TITLE
[Bug]: Soaryn Box may lose contents of inventory after game crashes due to unrelated error

### ISSUE THREAD

**Issue by SirWoofie** [Soaryn/XyCraftTracker#47]
### Mod Title

XyCraft Machines

### Minecraft Version

1.21.0

### Severity

Odd Results

### NeoForge Version

21.0.42-beta

### Describe the Suggestion

After experiencing a crash from another mod, one of my 4 Soaryn Boxes that had items in it was suddenly empty upon rejoining the world. I've had this happen twice when another mod crashed on two different Soaryn Boxes. Both times, a chunk contained two Boxes but only one of them was wiped. The contents of a chest within those same chunks were unaffected.

I've crashed more than twice due to another mod, but have only lost a Box's contents twice.

Theoretically, data loss shouldn't occur as the game saves before it exits due to the crash, right?

If you're curious about the other mod's crash and the crash report, you can find it in this issue with Relics: https://github.com/SSKirillSS/relics/issues/148#issue-2385071815

### Reproduction Steps

1. Place a Soaryn Box, fill it with some items.
2. Crash the game
3. Observe a Soaryn Box. It may suddenly be empty. Or it may not.

**Comment by Soaryn** [comment]
That sounds more like a side effect from crashing depending on when the box's contents were mutated. Crashes dont necessarily save the level

**Comment by Soaryn** [comment]
There at least was a typo in the code I had on newly placed Soaryn Boxes, but that should mean it was still calling the save method (just differently). I've changed it now regardless. I'm not sure how much resiliency I can add to the game for the event of crashing though. Given that, typically, when the game crashes it is stopping on that line, most often on the server side (the side in charge of saving).

Will push another build this week, and with any luck that fixes your issue.

**Comment by Soaryn** [comment]
Seemingly can't replicate this. Not sure this is something I can handle though.

**Comment by SirWoofie** [comment]
Thanks for taking a look at it! I haven't had my boxes lose their contents after a crash again, so I'm starting to suspect it was a side effect of the crash after all. Just thought I'd raise it since I had it happen twice.

**Comment by Soaryn** [comment]
Closing as this seems, as far as I can tell, resultant from crashing :)

**Comment by Soaryn** [comment]
Found a cause! This was due to the codec when deserializing the storage with an item that was broken. This is now more robust and should also allow you to remove and add a mod freely. Fixed in `0.7.30`. In a ideal scenario, you'd never see it. If an Item causes the crash, you would.

**Comment by Soaryn** [comment]
Ok in the public build this is still happening on enchanted items due to a Woopsies on my part and not noticing Neo changed something with the serialization path. Will be fixed in `0.7.32+` but won't be out until tomorrow or Thursday at the earliest
