### ISSUE TITLE
Matte Bricks break & hit particles has tint

### ISSUE THREAD

**Issue by nikita488** [Soaryn/XyCraftTracker#5]
**Describe the bug**
When breaking or mining any Matte Bricks block, the particles it spawns is colored.

**To Reproduce**
1. Break any of the Matte Bricks blocks
2. See error

**Expected behavior**
The block don't have tinted quads, it's just a simple texture, so the particles should have just texture applied without color.

**Screenshots**
![image](https://user-images.githubusercontent.com/6237881/187684198-40f75547-67c1-44fd-ad0f-1cbf67602b02.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - XyCraft Core Version: v0.5.1

**Comment by Soaryn** [comment]
Ah! In making the block a spawnable state I inadvertently gave it a tint. Will fix

**Comment by Soaryn** [comment]
Fixed in 0.5.2+
