### ISSUE TITLE
[Bug]: Crash with SecurityCraft Projector slot

### ISSUE THREAD

**Issue by Lolothepro** [Soaryn/XyCraftTracker#52]
### Mod Title

XyCraft Machines

### Minecraft Version

1.21.0

### Severity

Crashing

### NeoForge Version

21.0.78-beta

### Describe the Suggestion

Add a machine in a SecurityCraft projector crashes the game

https://github.com/Soaryn/XyCraftTracker/assets/68275908/e3d699e6-53a5-46f5-8ea9-bb3744febb7a

### Reproduction Steps

Reproduce the crash as in the video

### Additional Context

[2024-07-09-2.log](https://github.com/user-attachments/files/16144612/2024-07-09-2.log)

**Comment by Soaryn** [comment]
Have you reported this to Security craft, as it seems they are passing in null for the level which would fail a lot of things.

**Comment by Soaryn** [comment]
That being said you have the experimental Feature Flags enabled, so may want to not have that world for playing nor should that block be used as I can't make guarantees it will keep your world in working order.
I've added a null check for now, though Security Craft should not be sending `null` for a level, but rather a fake level.

**Comment by Lolothepro** [comment]
> Have you reported this to Security craft, as it seems they are passing in null for the level which would fail a lot of things.

Yeap

They said:

> Hm, on first glance I'd argue it's a XyCraft bug, since they aren't doing a safety null check (a similar crash should occur when trying to create a superflat world with an Engineering Table as a layer)

> I agree - the level parameter for the BlockAndTintGetter is marked as being nullable, which means a null check is necessary before using it.
> We can fix this on our side, however that may come with other side effects. This crash happens when trying to color a block in the state selector (the same way the model of the grass block is green). Since that block model does not actually belong to a physical block in the world, we can't really not pass null, since passing any non-null value implies that the block exists in the world.
> 
> The way grass blocks fix this is they provide a default color when they do not exist in a world (i.e. null is passed) where they can check for the biome and then use a specific grass color.

**Comment by Soaryn** [comment]
This will be (mostly solved) in the next version. I will say though, most "facade" rendering to properly render something needs to do so essentially in a fake world or similar to correctly have things like connected textures function properly.

**Comment by Soaryn** [comment]
Solved in `0.7.29` Null checks were added to prevent crashes, but to properly render these blocks (and many more) level and block positions should be passed in.

**Comment by bl4ckscor3** [comment]
Thanks for fixing the issue! I just want to preface this to say I'm posting this for completeness and not to start a discussion, critique something, or similar.

> to properly render these blocks (and many more) level and block positions should be passed in

Connected textures are irrelevant here, as this is a case of rendering a single block model in a UI where no world and no position exists. It's a preview render of the block state that will be used for the fake blocks in the world. [When we actually render the fake blocks into the world, we pass the level and position properly.](https://github.com/Geforce132/SecurityCraft/blob/1.21/src/main/java/net/geforcemods/securitycraft/renderers/ProjectorRenderer.java#L57) Vanilla actually calls the BlockAndTintGetter's method with null parameters as well in some part of its code (can't check where, I'm not at my PC) so it's theoretically possible for this crash to happen without SecurityCraft or other mods as well.
