### ISSUE TITLE
[Compatibility] buffer_side.png should be renamed to avoid issues with Iris/Optifine

### ISSUE THREAD

**Issue by IMS212** [Soaryn/XyCraftTracker#54]
When Iris loads textures, it checks for textures ending in `_n` and `_s` based off the Optifine format and assigns them as normal and specular textures for the main one.

Since there is `buffer_side.png` and `buffer_side_n.png`, it assigns `buffer_side_n.png` as a normal texture for `buffer_side.png` and makes the north side textureless.

Fixing this is rather simple; renaming the base texture (`buffer_side`) that it's trying to replace will let Iris know this is not a normal/specular texture.

**Comment by Soaryn** [comment]
:\ that... seems flawed on the Optifine side really as mcmeta is a thing 😅 and could be used to indicate such relations

**Comment by Soaryn** [comment]
Fortunately, `buffer_side` looks to be a template of sorts for texturing, so I can remove/rename it. But for Iris I'd highly advise adding something like `.mcmeta` to indicate these file relations. Will push a build later tonight (`0.7.30+`).

**Comment by IMS212** [comment]
Sadly, it's impossible to avoid this, because every texture pack relies on this behavior. I've done my best on my side by not counting it as an override if the main texture isn't enough of a match; but in this case, it was.

**Comment by embeddedt** [comment]
Mod-provided assets could always be handled differently from user-provided texture packs. I do not think it is reasonable to expect modern Minecraft mods to uphold a 10-year-old standard with such a high chance of accidental misnaming like this.

**Comment by Soaryn** [comment]
The file name has been changed to `buffer_side_template` in `0.7.30` I would HIGHLY encourage you though, to update further to more modern practices of resource mapping. `.mcmeta` or even just the pack info for mods specifically. That way mods don't get just arbitrarily picked up by a name schema that is both 10 years old and rather opaque.
