### ISSUE TITLE
[Bug]: Dark Phantome Glass Viewer

### ISSUE THREAD

**Issue by NJM1564** [Soaryn/XyCraftTracker#57]
### Mod Title

XyCraft World

### Minecraft Version

1.21.0

### Severity

Odd Results

### NeoForge Version

21.0.117
Mod version: Dark Phantome Glass Viewer
Pack All the mods 10 10-0.19

### Describe the Suggestion

The Dark Phantome Glass Viewer should probably not be emitting light.

### Reproduction Steps

Place Dark Phantome Glass Viewer and let there be light.

### Screenshots and Videos

![Screenshot (10464)](https://github.com/user-attachments/assets/58dcc540-a092-450f-9ecb-e5271b09e605)
![Screenshot (10465)](https://github.com/user-attachments/assets/11f1312d-6416-451e-9b4a-fcbbb6f4c601)

**Comment by Soaryn** [comment]
Loool yep I noticed that On Forgecraft as well! I have a fix in dev, but have some things to clean up first before pushing a new build. I also noticed the dark viewer letting light in.

**Comment by NJM1564** [comment]
I kinda wish there was a way to toggle the light on and off. It would be an awesome way to disable spawners.

**Comment by Soaryn** [comment]
I'll look into it again. The last time I did, the calculation for light was a little slow and a bit hesitant to give that redstone toggles here. But maybe

**Comment by NJM1564** [comment]
Just throwing in a bit of half blind coding idea here but,
Perhaps create a control block for it. Once placed it checks connected glass and calculates a cubic light volume for it. That should be simple to toggle on and off. 
Just a bit of data stored in one cube shouldn't cause much problems unless massively over used. But no more than a chest would.
Or use the preexisting multi block code for it. No idea how hard that would hit the system though.

**Comment by Soaryn** [comment]
It is the lighting engine that is not the cleanest thing the world. The illumination field will prob serve mlst of the purpose of shat you want, but even it controlled by redstone I am having troubles with mc behaving smoothly to my standards

**Comment by Soaryn** [comment]
Fixed in new version coming out today.
