### ISSUE TITLE
[Bug]: i may have encountered a bug with extractors and Mekanism Logistic pipes causing some strange console spam 

### ISSUE THREAD

**Issue by Gh3ttoboy** [Soaryn/XyCraftTracker#59]
### Mod Title

XyCraft Machines

### Minecraft Version

1.21.0

### Severity

Odd Results

### NeoForge Version

NeoForge 21.0 .134-beta
XyCraft Machines 0.7.33

### Describe the Suggestion

I dont know what i could suggest for it

### Reproduction Steps

I have not encountered any performance issue on the server due to the extractor and logistic pipe setup but its probably best to atleast send in a ticket on here it could be a problem with xycraft, AE2 matter condensor or the Mekanism Logistic pipes but when i teleport to any of the coords on that screenshot it puts me right into the extractor

I was just using a bunch of extractors to generate cobble stone for AE2 Singularties and to fill up a drawer with cobble but i kept getting the spam massages in my console for the server, as shown in the screen shots, now im not sure if this was an issue with Xycraft or Mekanism and since thie occured with the Xycraft Machine Extractors i tried to post about it in here

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/9218d7d0-e878-42c0-9fab-ebc045748846)
![image](https://github.com/user-attachments/assets/8ac0379e-75fd-46f5-9825-76209489a53e)

**Comment by Soaryn** [comment]
This was something I noticed with just 2 vanilla chests connected with mek pipes, removing the origin point before the item reaches destination. Can you try that out of curiosity?
