### ISSUE TITLE
Wrong pack.mcmeta description

### ISSUE THREAD

**Issue by nikita488** [Soaryn/XyCraftTracker#6]
It has "examplemod resources" instead of "XyCraft World resources" or something. This can be seen on world creation in Data Packs window.
**P.S.** Also XyCraft Core still has lowercase 'c' as seen on screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/6237881/187737826-92eaf52c-8205-4949-944e-dbed4475eb1d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - XyCraft Core Version: v0.5.2

**Comment by Soaryn** [comment]
Fixed in v0.5.3+
I forgot to search "examplemod" for things such as this. That I forgot entirely to do. One day I should look over all my "TODO"s and see what I forgot 🙃
