### ISSUE TITLE
[Bug]: When using the balloon on a stick, cannot take off

### ISSUE THREAD

**Issue by Luminaire0** [Soaryn/XyCraftTracker#60]
### Mod Title

XyCraft Machines

### Minecraft Version

1.20.1

### Severity

Odd Results

### NeoForge Version

Forge 47.3.0

### Describe the Suggestion

How do you take off with the balloon on a stick?

### Reproduction Steps

Create balloon on a stick, place it down anywhere.  Try hitting space twice does not take off.

**Comment by Soaryn** [comment]
1.20.1 has a problem of no real way for mods to collaborate the flight method. It sounds like you have something installed that is turning off flight every tick. Should be, you place down balloon on a stick and then you can fly locally, but until 1.20.4 there wasnt a good way for mods to not step on others by accident.

**Comment by Soaryn** [comment]
As a note, 1.20.1 will not be seeing any updates, due to several MAJOR changes since that version (which is almost a year old 😂)
This isn't really a problem (or at least I can't replicate it in 1.21)
