### ISSUE TITLE
[Bug]: Void container deletes cards from Laser IO

### ISSUE THREAD

**Issue by NJM1564** [Soaryn/XyCraftTracker#62]
### Mod Title

XyCraft Machines

### Minecraft Version

1.21.0

### Severity

Odd Results

### NeoForge Version

21.0.5.151

### Describe the Suggestion

Don't let it do that?

### Reproduction Steps

Place a Laser IO down. Place a Void container on it. Put cards in the Laser IO watch them vanish in smoke. Kinda funny that it only does that in the slot that points to the Void.

**Comment by Soaryn** [comment]
While not technically a bug, I will forward it to dire for him to tag his blocks for that not to happen.
