### ISSUE TITLE
[Bug]: Possible EMI compat issue

### ISSUE THREAD

**Issue by Saereth** [Soaryn/XyCraftTracker#63]
### Mod Title

XyCraft Machines

### Minecraft Version

1.21.0

### Severity

Crashing

### NeoForge Version

Mc 1.21.1
Neoforge: 21.1.22

### Describe the Suggestion

I opened an issue with EMI as well as I'm not quite sure where the issue lies;
https://github.com/emilyploszaj/emi/issues/674

### Reproduction Steps

mc: 1.21.1
Neoforge: 21.1.22
JEI: jei-1.21.1-neoforge-19.8.4.113
EMI: emi-1.1.11+1.21+neoforge
Stellaris: stellaris-1.21-neoforge-1.0.5
Xycraft: xycraft_core-0.7.45-all
xycraft_machines-0.7.45
xycraft_world-0.7.45

So what happens is when you search for oil in EMI the game crashes. If I remove stellaris it's fine but I dont have any other mods that add a liquid to know if its related to stellaris at all (I suspect not as we've had a similar crash searching for tritium with mekanism in the pack). Adding the xycraft mods along with EMi causes the crash to occur. Without Xycraft the crash doesnt occur and using JEI alone without EMI will cause the crash not to occur.

Here is the crash log

https://mclo.gs/NlmXqzM

**Comment by Soaryn** [comment]
No idea what is happening there, our flhids dont do anything spectacular or custom really. I have an "Oil" registered, but that shouldnt be causing issues here. What *is* stellaris?

**Comment by Soaryn** [comment]
Curiously, what does the creative tab look like for XyCraft foils without emi?

**Comment by Soaryn** [comment]
Notes put on the EMI issue page, but will note them here as well:
This is a Stellaris (and likely an Architectury) bug:
![image](https://github.com/user-attachments/assets/53a578f0-30a7-46d1-986c-fb5dbcabf2cd)
A fluid texture SHOULD be present as per the documentation. 

![image](https://github.com/user-attachments/assets/ca670fdc-0340-4c80-bad5-c0393e3bf8b5)

**Comment by Saereth** [comment]
took this over to the stellaris devs, thanks for checking in on it
