### ISSUE TITLE
[Bug]: Lava extractor recipe is upside down

### ISSUE THREAD

**Issue by Saereth** [Soaryn/XyCraftTracker#66]
### Minecraft Version

1.21.0

### Severity

Odd Results

### NeoForge Version

21.1.6

### Describe the Suggestion

The JEI recipe for lava extraction shows lava under drip stone under the extractor, this seems to be reverse of what is actually required
<img width="358" alt="image" src="https://github.com/user-attachments/assets/92ab670c-3fdd-474b-ac0a-82fbc148be7b">

### Reproduction Steps

Place a drip stone on lava and then the extract on the drip stone with a tank on top, no lava is produced, reverse it and it works

### Screenshots and Videos

<img width="1364" alt="image" src="https://github.com/user-attachments/assets/79e4e439-8d88-4d8a-8dff-aa55455486f9">

**Comment by Soaryn** [comment]
Not a bug, just unclear JEI instructions. The green cube is showing which orientations are correct of the left image. So... in this case flip it all upside down. This is something we are handling in a future version. Waiting on Gander

**Comment by Saereth** [comment]
ok sounds good, feel free to close then and i'll add a tooltip or something for some help for newer players. Ty for the quick response!

**Comment by Soaryn** [comment]
Still being worked on, just not exactly a bug. Sorry to anyone this causes inconveniences for.
