### ISSUE TITLE
[Bug]: Fabricator ignore special recipes deleting result item / persistent ingredients

### ISSUE THREAD

**Issue by DevDyna** [Soaryn/XyCraftTracker#67]
### Mod Title

XyCraft Machines

### Minecraft Version

1.20.1

### Severity

Odd Results

### NeoForge Version

Forge 47.3.11

### Describe the Suggestion

Fabricator can delete recipe ingredients that aren't consumed

### Reproduction Steps

1. Configure the fabricator like [Screen 1] and set on High Signal
2. Add input ingredients and the item that cannot be consumed [Screen 2]
3. Change the fabricator mode on Always On and see that it have consumed the original book (it persist on any recipes inclused custom with same logic) [Screen 3]

### Screenshots and Videos

# [Screen 1]
![2024-10-18_15 12 50](https://github.com/user-attachments/assets/918107b4-3095-4654-8a2b-82518c023c51)

# [Screen 2]
![2024-10-18_15 13 05](https://github.com/user-attachments/assets/83147a94-fb3c-4218-8574-7031e2c2f1c6)

# [Screen 3]
![2024-10-18_15 13 11](https://github.com/user-attachments/assets/a342a3e4-cd8a-4db3-a74d-a33c50d063c7)

![2024-10-18_15 33 07](https://github.com/user-attachments/assets/40a4cad1-8473-4824-baab-34d7b6f9e7e7)

**Comment by Soaryn** [comment]
Mmm will need to check after the weekend, but how are the ingredients specified as "not consumed". If memory serves I handled that. Buckets for instance are handled via the stack I think, but this also handles other cases It hough of special recipes.

**Comment by DevDyna** [comment]
> but how are the ingredients specified as "not consumed" in the recipe itself for thos recipe?

I have tested with a few of other special recipes and only one dont want to work -> banner cloning 

also apparently that recipes are completly broken on any other "crafter"

#
except that i have try with other mods
- mystical agriculture infusion stone custom recipe (work without problems)
- pedestal upgrade base recipe (work without problems)
- kubejs -> ( it dont work but probably caused from https://github.com/KubeJS-Mods/KubeJS/issues/913 )

**Comment by Soaryn** [comment]
OH! I just read 1.20.1 that is the wild west of bugs I feel for Xy as that isnt updated anymore 😅 So this is likely a bug, but should no longer be an issue if it was

**Comment by Soaryn** [comment]
Do you have an example of a vanilla recipe that has this behaviour? I designed the fabricator to work with things like cookware from `pam's`, etc. but wanted to check if it is working correctly in 1.21. 1.20.1 is very much a unsupported version at this point with all of the gradle changes I have made 😅

**Comment by DevDyna** [comment]
> Do you have an example of a vanilla recipe that has this behaviour?

book cloning was one of that but apparently every 1.20.1 bug persist on 1.21.1

## [Forge 1.20.1]
![2024-11-26_13 28 22](https://github.com/user-attachments/assets/30fc0752-1a93-4154-8bb4-1bf25a0f2380)
## [Neo 1.21.1]
![2024-11-26_13 33 27](https://github.com/user-attachments/assets/80bcc49b-ff97-416a-9784-c913ca156b06)



# Complete list of recipe broken on fabricator

### recipe that persist without execute the recipe
- banner cloning

### recipe that execute but ignore nbt result
- armor dye
- firework star & rocket
- shield decoration (banner + shield)
- tipped arrow
- suspicious stew
- decorated pots (using sherds on recipe pattern grid)
- trasmute items (like shulker box)

**Comment by Soaryn** [comment]
For the first one (banner) try making one of the slots "strict" by ctrl clicking it. If you don't HAVE a control key, you will need to rebind in settings first :P

Shulker boxes are doing what I'd expect really.
![image](https://github.com/user-attachments/assets/4a16e280-d292-47c8-b64a-4346ef17817f)
![image](https://github.com/user-attachments/assets/782880d9-5b04-4523-9416-782295726ab6)


That being said, cloning books does present a problem. Part of this is me wanting the fabricator to put back the items such as empty buckets BACK into the source they found them in. This will involve a much longer fix, but a bandaid seems to work for the moment for the more simple recipes:
![image](https://github.com/user-attachments/assets/72bd9659-fe3f-4e59-ba0e-28b12ac9e6e3)
This will likely be `1.21.3+` but there is a possibility at the very least to be back ported to `1.21.1`. Depends on time.

**Comment by Soaryn** [comment]
Ok, the long route wasn't as long as I expected. It SHOULD be more robust which will allow a little more control on the user side when dealing with external inventories. So a bucket will empty and place the empty bucket back in the original slot if it can (assuming there is no other stackable option present). This means using something like the buffer will be a little easier to guess where a remainder will wind up if used early. 

This does however, require mods to make sure that they write their `getRemainingItems` for their custom recipes correctly. Will keep testing, but with a minimal testing and no JEI in dev, it will be low priority for now

**Comment by DevDyna** [comment]
> For the first one (banner) try making one of the slots "strict" by ctrl clicking it. If you don't HAVE a control key, you will need to rebind in settings first :P

tested with "strict mode" and completly delete the banner *empty*

> Shulker boxes are doing what I'd expect really.

with same input dye work , but if added a different dye it try to color it ignoring that wasn't the same

tested a few about that and it keep on consume any dye inside coloring the same shulker until it was the same color of result

![image](https://github.com/user-attachments/assets/c2e7e71a-8ca7-487c-8cfe-6f329c1b3962)

![image](https://github.com/user-attachments/assets/dc570008-1c2a-4149-8236-8965089e7f85)

**Comment by Soaryn** [comment]
As weird as the shulker box one is, that is vanilla recipe being vanilla. It is one of the reasons I added the strict mode. 

I'll check banners again, but it was working as the recipe indicated

**Comment by Soaryn** [comment]
Can you get me an example of the banner recipe you are trying?

**Comment by DevDyna** [comment]
> Ah so like this one?

yes

**Comment by Soaryn** [comment]
Marking as completed then as fixed in dev in `1.21.3` 😊 
Still working on other attributes in my porting, but depending on how MC's changes changed that file may not be back portable to `1.21.1`. At the moment, it is leaning towards only forward movement.
