### ISSUE TITLE
[Suggestion]: add config option to disable specific ore generation

### ISSUE THREAD

**Issue by Zurkie** [Soaryn/XyCraftTracker#70]
### XyCraft Module

World

### Describe the Suggestion

a config option to disable common ore generation (specifically aluminum) would be nice to have

**Comment by Soaryn** [comment]
This is driven by data packs for Minecraft. Config options aren't really the way to go for world generation or recipes now a days :) I have no idea how to do it, but I do know you could even override it in some manner to make it more common, rare, non-existent, etc. The down side is that there is no in game method of setting this easily.
