### ISSUE TITLE
[Bug]: Resin Ball Recipe

### ISSUE THREAD

**Issue by sayrejeri** [Soaryn/XyCraftTracker#73]
### Mod Title

XyCraft Machines

### Minecraft Version

1.21.0

### Severity

Odd Results

### NeoForge Version

1.21.1

### Describe the Suggestion

No recipe for ATM10 Resin Ball or Resin Block, I can obtain it with the extractor and into a fluid drawer, but cant use a bucket on it at all and shows no ways to make it into a ball.

### Reproduction Steps

Just look at recipe page.

### Screenshots and Videos

[Minecraft NeoForge_ 1.21.1 2024-11-21 01-39-49VIDEO.zip](https://github.com/user-attachments/files/17840956/Minecraft.NeoForge_.1.21.1.2024-11-21.01-39-49VIDEO.zip)
Had to ZIP because video file is 12mb and it had to be 10mb?

**Comment by Soaryn** [comment]
Not exactly a bug, just more the resin, isn't really usable in the mod itself. It HAD a compat recipe with Create, but they haven't quite made it to 1.21.

All of the machines are still in progress

**Comment by Soaryn** [comment]
Iirc it was 1bucket to 1 block. It would be in now, but create updated to 1.21.1 well into our dev progress for 1.21.4+ so there likely wont be any fixes coming soon for that.
