### ISSUE TITLE
[Question]: Modifying worldgen data files for custom world via datapacks

### ISSUE THREAD

**Issue by YOYOK9** [Soaryn/XyCraftTracker#74]
### XyCraft Module

World

### Describe the Suggestion

This is more of a Question, I just wasn't sure if I should pick Bug, or Suggestion as the option. I apologize if this is the wrong place for this. 

I'm working on a custom datapack for a modpack I am working on, the datapack is loaded via Kubejs datapack management system. Because your mods are ARR and closed source, I wanted to ask your permission first before I started working on custom generation for this new world. 

Most of the other mods I have tweaked via custom feature placement datapacks or biome tags to get them to spawn properly in the new world. It is an overworld based world, just the Y values of ores has been altered. 

If it is alright with you, the only thing I would likely need a hand with is the Kivi stone type spawning. The rest would be normal custom feature placements coded to follow what I did for the vanilla ores. 

Otherwise would it be possible to get datapack support officially? I don't want to do something that could potentially get me in trouble.. 

### Additional Context

I know that in full technicality I could just open the mods jar and see how its done, then move to a datapack. But I don't feel overly comfortable doing that as your code is closed source and the mod ARR. I don't want to make enemies as a pack dev. It never ends well from what I've seen around the community. 

At this time I haven't coded anything related to the mod, I wanted to ask first.

Thank you for your time. If you are not comfortable with this, please let me know. I will leave XYCraft spawns alone till I hear back :)

**Comment by Soaryn** [comment]
Ah! I can't do it tonight, but I should probably put a light copy of the data pack entries here somewhere... 🤔 Prob sometime after Monday

**Comment by YOYOK9** [comment]
Sounds good, thank you for the quick reply. Will hold off on any work till you have something posted (just to be safe). :)
