### ISSUE TITLE
[Suggestion]: Add REI support

### ISSUE THREAD

**Issue by vizthex123** [Soaryn/XyCraftTracker#75]
### XyCraft Module

Machines

### Describe the Suggestion

[REI](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items) is the best remake of NEI imo, and it'd be great if this mod had native support for it.

I'm pretty sure only Machines has a tab, but if any others are added in the future it'd be nice if they all had REI support.

_Also, the link to the other modules on XyCraft core's page is broken._

**Comment by vizthex123** [comment]
yeah, the links on the CF page try to go to the backend settings instead of the public page.

i was really hoping there'd be REI support, rip. Oh well.

hopefully the [JEI compat](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items-hacks) add-on gets ported soon (and i'm damn near praying REI becomes the new standard cuz it's way better than JEI imo).

**Comment by Soaryn** [comment]
> yeah, the links on the CF page try to go to the backend settings instead of the public page.

Should be fixed now :)

> praying REI becomes the new standard 

That is HIGHLY unlikely to happen. The API side of it is ... not ideal. Especially if you can't give any practical examples of what it provides that JEI doesn't.

**Comment by vizthex123** [comment]
That's fine. Just figured i'd ask about it. Most of the reason i like it is just random quality-of-life stuff i'm sure most people don't notice/care about lol.

**Comment by Soaryn** [comment]
Again lol such as?

**Comment by Soaryn** [comment]
No example of any practical benefits provided. JEI (1.21) has had a LOT of improvements from the past versions. I recommend trying it out. Mezz is always accepting feedback on how to improve it, so I'd much rather support improving JEI than adding another fracture.
