### ISSUE TITLE
[Bug]: 1.21 Extractor moved without calling OnRemove error when teleporting into an area

### ISSUE THREAD

**Issue by SteveHeist** [Soaryn/XyCraftTracker#76]
### Minecraft Version

1.21.1

### Severity

Odd Results

### NeoForge Version

21.1.83

### Describe the Issue

Extractor throws the error when teleporting into the area / the first time the chunk is loaded.

### Reproduction Steps

Place an extractor.
Unload the chunks (example, go 20,000 blocks agway and log out of the game / close the server, then reopen the server and relog)
Teleport back to the chunks

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/d14a857a-0b85-4fdb-be3c-3883655dcc00)

### Additional Context

All versions of Xycraft (Core, Machines, et Al.) are 0.7.45

**Comment by Soaryn** [comment]
Hmm I assume something else potentially caused this then with you closing it?😅

**Comment by SteveHeist** [comment]
Yeah, discovered it was caused by a server crash rolling back the chunk, in turn outright *deleting* the Extractor. I figured closing was the closest thing to deleting.

Sent from Proton Mail Android

-------- Original Message --------
