### ISSUE TITLE
[Bug]: [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"xycraft_world:kivi_tiles"}]'

### ISSUE THREAD

**Issue by mathgtc** [Soaryn/XyCraftTracker#77]
### Mod Title

XyCraft World

### Minecraft Version

1.21.1

### Severity

Crashing

### NeoForge Version

21.1.90

### Describe the Issue

[Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"xycraft_world:kivi_tiles"}]'

it causes laags

[Server thread/WARN] [net.minecraft.server.MinecraftServer/]: Can't keep up! Is the server overloaded? Running 5955ms or 119 ticks behind

then the server is crashing after this error 

we built a lot of struktues with kivi tiles, so i changed it. 
but this wasnt the issue 

### Reproduction Steps

idk i have to find out where its come from 

[latest.log](https://github.com/user-attachments/files/18227572/latest.log)

**Comment by Soaryn** [comment]
Kivi tiles wouldn't cause this at all... they are just blocks like stone or dirt 😂
My GUESS is something is erroring when routing an item in a pipe or something similar and just that happens to be what is being transferred. You have an auto crafter somewhere making those?
