### ISSUE TITLE
Material colors of all blocks is inconsistent on the Map

### ISSUE THREAD

**Issue by nikita488** [Soaryn/XyCraftTracker#9]
**Describe the bug**
All blocks use default material color from properties copied/setted for blocks.

**To Reproduce**
1. Place all blocks from World module
2. Get a Map item and populate it with Right click
3. See error

**Expected behavior**
All blocks should have similar material color for them to be properly displayed on the Map. So Blue Kivi Bricks should have blue dot on the Map, Red Kivi Bricks should have red dot on the map, same for all other colors including different types of ores and RGB blocks. And non-cloud blocks like Kivi and Aluminum Blocks should have similar very dark/light color dots on the map too.

**Screenshots**
Placed in-world blocks:
![image](https://user-images.githubusercontent.com/6237881/188139880-9d1be5b8-80d6-480f-ae23-a87535440975.png)
Result on Map:
![image](https://user-images.githubusercontent.com/6237881/188139948-5135e70b-0239-429c-9f93-b697fa9c11bc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - XyCraft Core Version: v0.5.2

**Comment by Soaryn** [comment]
This was something I was looking at a few days ago, but considered it low enough priority to push back. My registry requires a slight change to handle this.

**Comment by Soaryn** [comment]
Going through the back log, this has been fixed in an upcoming release.
![image](https://user-images.githubusercontent.com/1859805/235287212-1d3d4d35-6d95-4d31-be92-4a4651b672f1.png)
